image_finetune: false

output_dir: "outputs/20_percent"
pretrained_model_path: "/home/dungnt206/workspace/huggingface/stable-diffusion-2-1-base" ##"models/StableDiffusion/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 2 #1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

name_dataset: smth2smth
train_data:
  csv_path:     "/home/dungnt206/workspace/data/something_something_v2/data/labels/train_valid_20_percent.json"
  video_folder: "/home/dungnt206/workspace/data/something_something_v2/data/20bn-something-something-v2"
  sample_size:     128 #256
  sample_stride:   2
  sample_n_frames: 32

validation_data:
  # prompts_for_metrics: "/home/dungnt206/workspace/data/something_something_v2/data/labels/2088_validate.json"
  prompts: [
    "squeezing paper",
    "pretending to open a gate without actually opening it",
    "scooping rice up with spoon",
    "plugging charger into laptop",
    "pulling a lotion bottle from left to right",
    "dropping paperclip into cup"
  ]
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: "/home/dungnt206/workspace/code/AnimateDiff/outputs/20_percent/training_smth_curated_20-2024-12-10T22-57-18/checkpoints/checkpoint-epoch-84.ckpt"

learning_rate:    5.e-5 ##1.e-4
train_batch_size: 1 ## 4

max_train_epoch:      -1
max_train_steps:      1 #100
checkpointing_epochs: -1
checkpointing_steps:  1 #60

validation_steps:       1 ## 500
validation_steps_tuple: [1, 1] #[2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False
