image_finetune: false

output_dir: "outputs"
pretrained_model_path: "/vinai/dungnt206/stable-diffusion-2-1-base" ##"models/StableDiffusion/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

name_dataset: smth2smth
train_data:
  csv_path:        "/home/ubuntu/video-generation/something_something_v2/data/labels/20_class_train.json"
  video_folder:    "/home/ubuntu/video-generation/something_something_v2/data/20bn-something-something-v2"
  sample_size:     128 #256
  sample_stride:   2
  sample_n_frames: 16

validation_data:
  prompts: [
    'dropping pen next to bottle',
    'holding spoon next to bowl',
    'holding black bottle',
    'spinning a pen so it continues spinning',
    'dropping alarm clock into bowl',
    'putting bottle and pen on the table',
    'pulling a doll from right to left',
    'pulling plastic bottle from right to left',
    'pulling candle from behind of laptop',
    'poking plastic bottle so that it falls over',
    'poking hard plastic toy ball so that it falls over',
    'pushing wrap so that it slightly moves',
    'throwing box in the air and letting it fall'
    ]
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    1.e-4
train_batch_size: 6 ## 4

max_train_epoch:      20
max_train_steps:      -1 #100
checkpointing_epochs: 2
checkpointing_steps:  -1 #60

validation_steps:       14000 ## 500
validation_steps_tuple: [5000, 10000] #[2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False
